import type { Metadata } from 'next';
import { cn } from '@/lib/utils';
import { Inter } from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Lyra - Your PDF conversation',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="light">
            <body
                suppressHydrationWarning={true}
                className={
                    (cn('min-h-screen font-sans antialiased grainy'),
                    inter.className)
                }
            >
                {children}
            </body>
        </html>
    );
}
